// Code generated by compiler/clang. DO NOT EDIT.

//go:build cgo

package main

/*
#include <stdint.h>
#include <stddef.h>
typedef struct {
int8_t f0;
double f1;
int16_t f2;
} dylib_go_5061636b656442696e64696e6773_record0;
static uint64_t dylib_go_5061636b656442696e64696e6773_record0_layout(int32_t index) {
switch(index) {
case 0:return sizeof(dylib_go_5061636b656442696e64696e6773_record0);
case 1:return _Alignof(dylib_go_5061636b656442696e64696e6773_record0);
case 2:return offsetof(dylib_go_5061636b656442696e64696e6773_record0,f0);
case 3:return offsetof(dylib_go_5061636b656442696e64696e6773_record0,f1);
case 4:return offsetof(dylib_go_5061636b656442696e64696e6773_record0,f2);
default:return UINT64_MAX;
}
}
typedef dylib_go_5061636b656442696e64696e6773_record0 (*dylib_go_5061636b656442696e64696e6773_call0_function)(dylib_go_5061636b656442696e64696e6773_record0);
static dylib_go_5061636b656442696e64696e6773_record0 dylib_go_5061636b656442696e64696e6773_call0(uintptr_t address,dylib_go_5061636b656442696e64696e6773_record0 p0) {
return ((dylib_go_5061636b656442696e64696e6773_call0_function)address)(p0);
}
*/
import "C"

import (
	"fmt"
	dylib "github.com/cpunion/dylib-go"

	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
)

var _PackedBindingsDeclarations = clang.Header{
	Target: clang.Target{Triple: "aarch64-pc-windows-msvc", OS: "windows", Arch: "arm64", PointerSize: 8},
	Functions: []clang.Declaration{
		{Name: "echo_pair", Symbol: "echo_pair", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}},
	},
	Records: []clang.Record{
		{Name: "Pair", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}, Layout: abi.Layout{Size: 11, Alignment: 1, Offsets: []uint64{0, 1, 9}}},
	},
}

// PackedBindingsRecord0 describes Pair; pointer fields are caller-managed native addresses.
//
//llgo:type C
type PackedBindingsRecord0 struct {
	Tag   int8
	Value float64
	Tail  int16
}

func _PackedBindingsRecord0ToC(value PackedBindingsRecord0) (result C.dylib_go_5061636b656442696e64696e6773_record0) {
	result.f0 = C.int8_t(value.Tag)
	result.f1 = C.double(value.Value)
	result.f2 = C.int16_t(value.Tail)
	return result
}

func _PackedBindingsRecord0FromC(value C.dylib_go_5061636b656442696e64696e6773_record0) (result PackedBindingsRecord0) {
	result.Tag = int8(value.f0)
	result.Value = float64(value.f1)
	result.Tail = int16(value.f2)
	return result
}

// PackedBindings retains symbol handles; its caller owns the Session.
type PackedBindings struct {
	symbol0 *dylib.Symbol
}

// NewPackedBindings validates the host and resolves each requested export.
func NewPackedBindings(session *dylib.Session) (*PackedBindings, error) {
	if session == nil {
		return nil, dylib.ErrClosed
	}
	if err := _PackedBindingsDeclarations.Target.CheckHost(); err != nil {
		return nil, err
	}
	b := &PackedBindings{}
	if uint64(C.dylib_go_5061636b656442696e64696e6773_record0_layout(0)) != 11 || uint64(C.dylib_go_5061636b656442696e64696e6773_record0_layout(1)) != 1 || uint64(C.dylib_go_5061636b656442696e64696e6773_record0_layout(2)) != 0 || uint64(C.dylib_go_5061636b656442696e64696e6773_record0_layout(3)) != 1 || uint64(C.dylib_go_5061636b656442696e64696e6773_record0_layout(4)) != 9 {
		return nil, fmt.Errorf("clang: compiler/cgo layout mismatch for Pair")
	}
	symbol0, err := session.Resolve("echo_pair")
	if err != nil {
		return nil, err
	}
	b.symbol0 = symbol0
	return b, nil
}

func (b *PackedBindings) Echo_pair(p0 PackedBindingsRecord0) (result PackedBindingsRecord0, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol0.WithAddress(func(address uintptr) error {
		result = _PackedBindingsRecord0FromC(C.dylib_go_5061636b656442696e64696e6773_call0(C.uintptr_t(address), _PackedBindingsRecord0ToC(p0)))
		return nil
	})
	return result, err
}
