// Code generated by compiler/clang. DO NOT EDIT.

//go:build cgo

package main

/*
#include <stdint.h>
typedef int32_t (__attribute__((stdcall)) *dylib_go_436f6e76656e74696f6e73_call0_function)(int32_t,int32_t);
static int32_t dylib_go_436f6e76656e74696f6e73_call0(uintptr_t address,int32_t p0,int32_t p1) {
return ((dylib_go_436f6e76656e74696f6e73_call0_function)address)(p0,p1);
}
typedef double (__attribute__((stdcall)) *dylib_go_436f6e76656e74696f6e73_call1_function)(int32_t,double,float,uint64_t);
static double dylib_go_436f6e76656e74696f6e73_call1(uintptr_t address,int32_t p0,double p1,float p2,uint64_t p3) {
return ((dylib_go_436f6e76656e74696f6e73_call1_function)address)(p0,p1,p2,p3);
}
typedef int32_t (__attribute__((fastcall)) *dylib_go_436f6e76656e74696f6e73_call2_function)(int32_t,int32_t);
static int32_t dylib_go_436f6e76656e74696f6e73_call2(uintptr_t address,int32_t p0,int32_t p1) {
return ((dylib_go_436f6e76656e74696f6e73_call2_function)address)(p0,p1);
}
typedef double (__attribute__((fastcall)) *dylib_go_436f6e76656e74696f6e73_call3_function)(int32_t,int32_t,double,float);
static double dylib_go_436f6e76656e74696f6e73_call3(uintptr_t address,int32_t p0,int32_t p1,double p2,float p3) {
return ((dylib_go_436f6e76656e74696f6e73_call3_function)address)(p0,p1,p2,p3);
}
typedef int32_t (__attribute__((stdcall)) *dylib_go_436f6e76656e74696f6e73_call4_pointer0)(int32_t,int32_t);
typedef dylib_go_436f6e76656e74696f6e73_call4_pointer0 (__attribute__((cdecl)) *dylib_go_436f6e76656e74696f6e73_call4_function)(void);
static void * dylib_go_436f6e76656e74696f6e73_call4(uintptr_t address) {
return (void *)((dylib_go_436f6e76656e74696f6e73_call4_function)address)();
}
typedef int32_t (__attribute__((fastcall)) *dylib_go_436f6e76656e74696f6e73_call5_pointer0)(int32_t,int32_t);
typedef dylib_go_436f6e76656e74696f6e73_call5_pointer0 (__attribute__((cdecl)) *dylib_go_436f6e76656e74696f6e73_call5_function)(void);
static void * dylib_go_436f6e76656e74696f6e73_call5(uintptr_t address) {
return (void *)((dylib_go_436f6e76656e74696f6e73_call5_function)address)();
}
typedef int32_t (__attribute__((stdcall)) *dylib_go_436f6e76656e74696f6e73_call6_pointer1)(int32_t,int32_t);
typedef int32_t (__attribute__((cdecl)) *dylib_go_436f6e76656e74696f6e73_call6_function)(dylib_go_436f6e76656e74696f6e73_call6_pointer1,int32_t,int32_t);
static int32_t dylib_go_436f6e76656e74696f6e73_call6(uintptr_t address,void * p0,int32_t p1,int32_t p2) {
return ((dylib_go_436f6e76656e74696f6e73_call6_function)address)((dylib_go_436f6e76656e74696f6e73_call6_pointer1)p0,p1,p2);
}
typedef int32_t (__attribute__((fastcall)) *dylib_go_436f6e76656e74696f6e73_call7_pointer1)(int32_t,int32_t);
typedef int32_t (__attribute__((cdecl)) *dylib_go_436f6e76656e74696f6e73_call7_function)(dylib_go_436f6e76656e74696f6e73_call7_pointer1,int32_t,int32_t);
static int32_t dylib_go_436f6e76656e74696f6e73_call7(uintptr_t address,void * p0,int32_t p1,int32_t p2) {
return ((dylib_go_436f6e76656e74696f6e73_call7_function)address)((dylib_go_436f6e76656e74696f6e73_call7_pointer1)p0,p1,p2);
}
typedef int32_t (__attribute__((fastcall)) *dylib_go_436f6e76656e74696f6e73_call8_pointer1)(int32_t,int32_t);
typedef int32_t (__attribute__((stdcall)) *dylib_go_436f6e76656e74696f6e73_call8_function)(dylib_go_436f6e76656e74696f6e73_call8_pointer1,int32_t,int32_t);
static int32_t dylib_go_436f6e76656e74696f6e73_call8(uintptr_t address,void * p0,int32_t p1,int32_t p2) {
return ((dylib_go_436f6e76656e74696f6e73_call8_function)address)((dylib_go_436f6e76656e74696f6e73_call8_pointer1)p0,p1,p2);
}
typedef int32_t (__attribute__((stdcall)) *dylib_go_436f6e76656e74696f6e73_call9_pointer1)(int32_t,int32_t);
typedef int32_t (__attribute__((fastcall)) *dylib_go_436f6e76656e74696f6e73_call9_function)(dylib_go_436f6e76656e74696f6e73_call9_pointer1,int32_t,int32_t);
static int32_t dylib_go_436f6e76656e74696f6e73_call9(uintptr_t address,void * p0,int32_t p1,int32_t p2) {
return ((dylib_go_436f6e76656e74696f6e73_call9_function)address)((dylib_go_436f6e76656e74696f6e73_call9_pointer1)p0,p1,p2);
}
*/
import "C"

import (
	dylib "github.com/cpunion/dylib-go"
	"unsafe"

	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
)

var _ConventionsDeclarations = clang.Header{
	Target: clang.Target{Triple: "i686-pc-windows-msvc", OS: "windows", Arch: "386", PointerSize: 4},
	Functions: []clang.Declaration{
		{Name: "std_add", Symbol: "std_add@8", Signature: abi.Signature{Result: abi.I32, Convention: abi.StdCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}},
		{Name: "std_mixed", Symbol: "std_mixed@24", Signature: abi.Signature{Result: abi.F64, Convention: abi.StdCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.F64, abi.F32, abi.U64}}},
		{Name: "fast_add", Symbol: "@fast_add@8", Signature: abi.Signature{Result: abi.I32, Convention: abi.FastCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}},
		{Name: "fast_mixed", Symbol: "@fast_mixed@20", Signature: abi.Signature{Result: abi.F64, Convention: abi.FastCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32, abi.F64, abi.F32}}},
		{Name: "std_factory", Symbol: "std_factory", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}, FunctionPointers: []clang.FunctionPointer{{Position: -1, Signature: abi.Signature{Result: abi.I32, Convention: abi.StdCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "fast_factory", Symbol: "fast_factory", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}, FunctionPointers: []clang.FunctionPointer{{Position: -1, Signature: abi.Signature{Result: abi.I32, Convention: abi.FastCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "apply_std", Symbol: "apply_std", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer, abi.I32, abi.I32}}, FunctionPointers: []clang.FunctionPointer{{Position: 0, Signature: abi.Signature{Result: abi.I32, Convention: abi.StdCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "apply_fast", Symbol: "apply_fast", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer, abi.I32, abi.I32}}, FunctionPointers: []clang.FunctionPointer{{Position: 0, Signature: abi.Signature{Result: abi.I32, Convention: abi.FastCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "std_apply_fast", Symbol: "std_apply_fast@12", Signature: abi.Signature{Result: abi.I32, Convention: abi.StdCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer, abi.I32, abi.I32}}, FunctionPointers: []clang.FunctionPointer{{Position: 0, Signature: abi.Signature{Result: abi.I32, Convention: abi.FastCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "fast_apply_std", Symbol: "@fast_apply_std@12", Signature: abi.Signature{Result: abi.I32, Convention: abi.FastCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer, abi.I32, abi.I32}}, FunctionPointers: []clang.FunctionPointer{{Position: 0, Signature: abi.Signature{Result: abi.I32, Convention: abi.StdCall, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
	},
}

// Conventions retains symbol handles; its caller owns the Session.
type Conventions struct {
	symbol0 *dylib.Symbol
	symbol1 *dylib.Symbol
	symbol2 *dylib.Symbol
	symbol3 *dylib.Symbol
	symbol4 *dylib.Symbol
	symbol5 *dylib.Symbol
	symbol6 *dylib.Symbol
	symbol7 *dylib.Symbol
	symbol8 *dylib.Symbol
	symbol9 *dylib.Symbol
}

// NewConventions validates the host and resolves each requested export.
func NewConventions(session *dylib.Session) (*Conventions, error) {
	if session == nil {
		return nil, dylib.ErrClosed
	}
	if err := _ConventionsDeclarations.Target.CheckHost(); err != nil {
		return nil, err
	}
	b := &Conventions{}
	symbol0, err := session.Resolve("std_add@8")
	if err != nil {
		return nil, err
	}
	b.symbol0 = symbol0
	symbol1, err := session.Resolve("std_mixed@24")
	if err != nil {
		return nil, err
	}
	b.symbol1 = symbol1
	symbol2, err := session.Resolve("@fast_add@8")
	if err != nil {
		return nil, err
	}
	b.symbol2 = symbol2
	symbol3, err := session.Resolve("@fast_mixed@20")
	if err != nil {
		return nil, err
	}
	b.symbol3 = symbol3
	symbol4, err := session.Resolve("std_factory")
	if err != nil {
		return nil, err
	}
	b.symbol4 = symbol4
	symbol5, err := session.Resolve("fast_factory")
	if err != nil {
		return nil, err
	}
	b.symbol5 = symbol5
	symbol6, err := session.Resolve("apply_std")
	if err != nil {
		return nil, err
	}
	b.symbol6 = symbol6
	symbol7, err := session.Resolve("apply_fast")
	if err != nil {
		return nil, err
	}
	b.symbol7 = symbol7
	symbol8, err := session.Resolve("std_apply_fast@12")
	if err != nil {
		return nil, err
	}
	b.symbol8 = symbol8
	symbol9, err := session.Resolve("@fast_apply_std@12")
	if err != nil {
		return nil, err
	}
	b.symbol9 = symbol9
	return b, nil
}

func (b *Conventions) Std_add(p0 int32, p1 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol0.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_436f6e76656e74696f6e73_call0(C.uintptr_t(address), C.int32_t(p0), C.int32_t(p1)))
		return nil
	})
	return result, err
}

func (b *Conventions) Std_mixed(p0 int32, p1 float64, p2 float32, p3 uint64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol1.WithAddress(func(address uintptr) error {
		result = float64(C.dylib_go_436f6e76656e74696f6e73_call1(C.uintptr_t(address), C.int32_t(p0), C.double(p1), C.float(p2), C.uint64_t(p3)))
		return nil
	})
	return result, err
}

func (b *Conventions) Fast_add(p0 int32, p1 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol2.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_436f6e76656e74696f6e73_call2(C.uintptr_t(address), C.int32_t(p0), C.int32_t(p1)))
		return nil
	})
	return result, err
}

func (b *Conventions) Fast_mixed(p0 int32, p1 int32, p2 float64, p3 float32) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol3.WithAddress(func(address uintptr) error {
		result = float64(C.dylib_go_436f6e76656e74696f6e73_call3(C.uintptr_t(address), C.int32_t(p0), C.int32_t(p1), C.double(p2), C.float(p3)))
		return nil
	})
	return result, err
}

func (b *Conventions) Std_factory() (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol4.WithAddress(func(address uintptr) error {
		result = unsafe.Pointer(C.dylib_go_436f6e76656e74696f6e73_call4(C.uintptr_t(address)))
		return nil
	})
	return result, err
}

func (b *Conventions) Fast_factory() (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol5.WithAddress(func(address uintptr) error {
		result = unsafe.Pointer(C.dylib_go_436f6e76656e74696f6e73_call5(C.uintptr_t(address)))
		return nil
	})
	return result, err
}

func (b *Conventions) Apply_std(p0 unsafe.Pointer, p1 int32, p2 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol6.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_436f6e76656e74696f6e73_call6(C.uintptr_t(address), p0, C.int32_t(p1), C.int32_t(p2)))
		return nil
	})
	return result, err
}

func (b *Conventions) Apply_fast(p0 unsafe.Pointer, p1 int32, p2 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol7.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_436f6e76656e74696f6e73_call7(C.uintptr_t(address), p0, C.int32_t(p1), C.int32_t(p2)))
		return nil
	})
	return result, err
}

func (b *Conventions) Std_apply_fast(p0 unsafe.Pointer, p1 int32, p2 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol8.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_436f6e76656e74696f6e73_call8(C.uintptr_t(address), p0, C.int32_t(p1), C.int32_t(p2)))
		return nil
	})
	return result, err
}

func (b *Conventions) Fast_apply_std(p0 unsafe.Pointer, p1 int32, p2 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol9.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_436f6e76656e74696f6e73_call9(C.uintptr_t(address), p0, C.int32_t(p1), C.int32_t(p2)))
		return nil
	})
	return result, err
}
