// Code generated by compiler/clang. DO NOT EDIT.

//go:build cgo

package main

/*
#include <stdint.h>
typedef int8_t (*dylib_go_42696e64696e6773_call0_function)(int8_t);
static int32_t dylib_go_42696e64696e6773_call0(uintptr_t address,int32_t p0) {
return ((dylib_go_42696e64696e6773_call0_function)address)((int8_t)p0);
}
typedef uint8_t (*dylib_go_42696e64696e6773_call1_function)(uint8_t);
static uint32_t dylib_go_42696e64696e6773_call1(uintptr_t address,uint32_t p0) {
return ((dylib_go_42696e64696e6773_call1_function)address)((uint8_t)p0);
}
typedef int16_t (*dylib_go_42696e64696e6773_call2_function)(int16_t);
static int32_t dylib_go_42696e64696e6773_call2(uintptr_t address,int32_t p0) {
return ((dylib_go_42696e64696e6773_call2_function)address)((int16_t)p0);
}
typedef uint16_t (*dylib_go_42696e64696e6773_call3_function)(uint16_t);
static uint32_t dylib_go_42696e64696e6773_call3(uintptr_t address,uint32_t p0) {
return ((dylib_go_42696e64696e6773_call3_function)address)((uint16_t)p0);
}
typedef int32_t (*dylib_go_42696e64696e6773_call4_function)(int32_t);
static int32_t dylib_go_42696e64696e6773_call4(uintptr_t address,int32_t p0) {
return ((dylib_go_42696e64696e6773_call4_function)address)(p0);
}
typedef uint32_t (*dylib_go_42696e64696e6773_call5_function)(uint32_t);
static uint32_t dylib_go_42696e64696e6773_call5(uintptr_t address,uint32_t p0) {
return ((dylib_go_42696e64696e6773_call5_function)address)(p0);
}
typedef int64_t (*dylib_go_42696e64696e6773_call6_function)(int64_t);
static int64_t dylib_go_42696e64696e6773_call6(uintptr_t address,int64_t p0) {
return ((dylib_go_42696e64696e6773_call6_function)address)(p0);
}
typedef uint64_t (*dylib_go_42696e64696e6773_call7_function)(uint64_t);
static uint64_t dylib_go_42696e64696e6773_call7(uintptr_t address,uint64_t p0) {
return ((dylib_go_42696e64696e6773_call7_function)address)(p0);
}
typedef float (*dylib_go_42696e64696e6773_call8_function)(float);
static float dylib_go_42696e64696e6773_call8(uintptr_t address,float p0) {
return ((dylib_go_42696e64696e6773_call8_function)address)(p0);
}
typedef double (*dylib_go_42696e64696e6773_call9_function)(double);
static double dylib_go_42696e64696e6773_call9(uintptr_t address,double p0) {
return ((dylib_go_42696e64696e6773_call9_function)address)(p0);
}
typedef _Bool (*dylib_go_42696e64696e6773_call10_function)(_Bool);
static int32_t dylib_go_42696e64696e6773_call10(uintptr_t address,int32_t p0) {
return ((dylib_go_42696e64696e6773_call10_function)address)((_Bool)p0);
}
typedef void * (*dylib_go_42696e64696e6773_call11_function)(void *);
static void * dylib_go_42696e64696e6773_call11(uintptr_t address,void * p0) {
return (void *)((dylib_go_42696e64696e6773_call11_function)address)(p0);
}
typedef int32_t (*dylib_go_42696e64696e6773_call12_function)(void);
static int32_t dylib_go_42696e64696e6773_call12(uintptr_t address) {
return ((dylib_go_42696e64696e6773_call12_function)address)();
}
typedef void (*dylib_go_42696e64696e6773_call13_function)(void);
static void dylib_go_42696e64696e6773_call13(uintptr_t address) {
((dylib_go_42696e64696e6773_call13_function)address)();
}
typedef double (*dylib_go_42696e64696e6773_call14_function)(int32_t,double,float,uint64_t);
static double dylib_go_42696e64696e6773_call14(uintptr_t address,int32_t p0,double p1,float p2,uint64_t p3) {
return ((dylib_go_42696e64696e6773_call14_function)address)(p0,p1,p2,p3);
}
typedef int32_t (*dylib_go_42696e64696e6773_call15_function)(int32_t,...);
static int32_t dylib_go_42696e64696e6773_call15(uintptr_t address,int32_t p0,int32_t p1,float p2) {
return ((dylib_go_42696e64696e6773_call15_function)address)(p0,(int8_t)p1,p2);
}
typedef int32_t (*dylib_go_42696e64696e6773_call16_function)(int32_t,...);
static int32_t dylib_go_42696e64696e6773_call16(uintptr_t address,int32_t p0,int32_t p1,uint32_t p2,int32_t p3,uint32_t p4,float p5,int32_t p6,int64_t p7,uint64_t p8,void * p9) {
return ((dylib_go_42696e64696e6773_call16_function)address)(p0,(int8_t)p1,(uint8_t)p2,(int16_t)p3,(uint16_t)p4,p5,(_Bool)p6,p7,p8,p9);
}
typedef int32_t (*dylib_go_42696e64696e6773_call17_function)(int32_t,...);
static int32_t dylib_go_42696e64696e6773_call17(uintptr_t address,int32_t p0) {
return ((dylib_go_42696e64696e6773_call17_function)address)(p0);
}
typedef int32_t (*dylib_go_42696e64696e6773_call18_function)(float,int32_t,...);
static int32_t dylib_go_42696e64696e6773_call18(uintptr_t address,float p0,int32_t p1,int32_t p2,float p3) {
return ((dylib_go_42696e64696e6773_call18_function)address)(p0,p1,(int8_t)p2,p3);
}
typedef void (*dylib_go_42696e64696e6773_call19_function)(int32_t,...);
static void dylib_go_42696e64696e6773_call19(uintptr_t address,int32_t p0,int32_t p1) {
((dylib_go_42696e64696e6773_call19_function)address)(p0,(int16_t)p1);
}
typedef int32_t (*dylib_go_42696e64696e6773_call20_pointer0)(int32_t,int32_t);
typedef dylib_go_42696e64696e6773_call20_pointer0 (*dylib_go_42696e64696e6773_call20_function)(void);
static void * dylib_go_42696e64696e6773_call20(uintptr_t address) {
return (void *)((dylib_go_42696e64696e6773_call20_function)address)();
}
typedef int32_t (*dylib_go_42696e64696e6773_call21_pointer1)(int32_t,int32_t);
typedef int32_t (*dylib_go_42696e64696e6773_call21_function)(dylib_go_42696e64696e6773_call21_pointer1,int32_t,int32_t);
static int32_t dylib_go_42696e64696e6773_call21(uintptr_t address,void * p0,int32_t p1,int32_t p2) {
return ((dylib_go_42696e64696e6773_call21_function)address)((dylib_go_42696e64696e6773_call21_pointer1)p0,p1,p2);
}
typedef int32_t (*dylib_go_42696e64696e6773_call22_pointer0)(int32_t,...);
typedef dylib_go_42696e64696e6773_call22_pointer0 (*dylib_go_42696e64696e6773_call22_function)(void);
static void * dylib_go_42696e64696e6773_call22(uintptr_t address) {
return (void *)((dylib_go_42696e64696e6773_call22_function)address)();
}
typedef int32_t (*dylib_go_42696e64696e6773_call23_pointer1)(int32_t,...);
typedef int32_t (*dylib_go_42696e64696e6773_call23_function)(dylib_go_42696e64696e6773_call23_pointer1,int32_t);
static int32_t dylib_go_42696e64696e6773_call23(uintptr_t address,void * p0,int32_t p1) {
return ((dylib_go_42696e64696e6773_call23_function)address)((dylib_go_42696e64696e6773_call23_pointer1)p0,p1);
}
typedef void * (*dylib_go_42696e64696e6773_call24_function)(void);
static void * dylib_go_42696e64696e6773_call24(uintptr_t address) {
return (void *)((dylib_go_42696e64696e6773_call24_function)address)();
}
*/
import "C"

import (
	dylib "github.com/cpunion/dylib-go"
	"unsafe"

	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
)

var _BindingsDeclarations = clang.Header{
	Target: clang.Target{Triple: "x86_64-unknown-linux-gnu", OS: "linux", Arch: "amd64", PointerSize: 8},
	Functions: []clang.Declaration{
		{Name: "s8", Symbol: "s8", Signature: abi.Signature{Result: abi.I8, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I8}}},
		{Name: "u8", Symbol: "u8", Signature: abi.Signature{Result: abi.U8, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U8}}},
		{Name: "s16", Symbol: "s16", Signature: abi.Signature{Result: abi.I16, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I16}}},
		{Name: "u16", Symbol: "u16", Signature: abi.Signature{Result: abi.U16, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U16}}},
		{Name: "s32", Symbol: "s32", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32}}},
		{Name: "u32", Symbol: "u32", Signature: abi.Signature{Result: abi.U32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U32}}},
		{Name: "s64", Symbol: "s64", Signature: abi.Signature{Result: abi.I64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I64}}},
		{Name: "u64", Symbol: "u64", Signature: abi.Signature{Result: abi.U64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U64}}},
		{Name: "f32", Symbol: "f32", Signature: abi.Signature{Result: abi.F32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F32}}},
		{Name: "f64", Symbol: "f64", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F64}}},
		{Name: "truth", Symbol: "truth", Signature: abi.Signature{Result: abi.Bool, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Bool}}},
		{Name: "pointer", Symbol: "pointer", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer}}},
		{Name: "zero", Symbol: "zero", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
		{Name: "empty", Symbol: "empty", Signature: abi.Signature{Result: abi.Void, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
		{Name: "mixed", Symbol: "mixed", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.F64, abi.F32, abi.U64}}},
		{Name: "variable", Symbol: "variable", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32, abi.I8, abi.F32}}},
		{Name: "promotions", Symbol: "promotions", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32, abi.I8, abi.U8, abi.I16, abi.U16, abi.F32, abi.Bool, abi.I64, abi.U64, abi.Pointer}}},
		{Name: "empty_variable", Symbol: "empty_variable", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32}}},
		{Name: "mixed_variable", Symbol: "mixed_variable", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 2, Args: []abi.Type{abi.F32, abi.I32, abi.I8, abi.F32}}},
		{Name: "void_variable", Symbol: "void_variable", Signature: abi.Signature{Result: abi.Void, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32, abi.I16}}},
		{Name: "adder_factory", Symbol: "adder_factory", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}, FunctionPointers: []clang.FunctionPointer{{Position: -1, Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "apply_adder", Symbol: "apply_adder", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer, abi.I32, abi.I32}}, FunctionPointers: []clang.FunctionPointer{{Position: 0, Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}}}},
		{Name: "variadic_factory", Symbol: "variadic_factory", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}, FunctionPointers: []clang.FunctionPointer{{Position: -1, Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32}}}}},
		{Name: "forward_variadic", Symbol: "forward_variadic", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer, abi.I32}}, FunctionPointers: []clang.FunctionPointer{{Position: 0, Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32}}}}},
		{Name: "data_pointer", Symbol: "data_pointer", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
	},
}

// Bindings retains symbol handles; its caller owns the Session.
type Bindings struct {
	symbol0  *dylib.Symbol
	symbol1  *dylib.Symbol
	symbol2  *dylib.Symbol
	symbol3  *dylib.Symbol
	symbol4  *dylib.Symbol
	symbol5  *dylib.Symbol
	symbol6  *dylib.Symbol
	symbol7  *dylib.Symbol
	symbol8  *dylib.Symbol
	symbol9  *dylib.Symbol
	symbol10 *dylib.Symbol
	symbol11 *dylib.Symbol
	symbol12 *dylib.Symbol
	symbol13 *dylib.Symbol
	symbol14 *dylib.Symbol
	symbol15 *dylib.Symbol
	symbol16 *dylib.Symbol
	symbol17 *dylib.Symbol
	symbol18 *dylib.Symbol
	symbol19 *dylib.Symbol
	symbol20 *dylib.Symbol
	symbol21 *dylib.Symbol
	symbol22 *dylib.Symbol
	symbol23 *dylib.Symbol
	symbol24 *dylib.Symbol
}

// NewBindings validates the host and resolves each requested export.
func NewBindings(session *dylib.Session) (*Bindings, error) {
	if session == nil {
		return nil, dylib.ErrClosed
	}
	if err := _BindingsDeclarations.Target.CheckHost(); err != nil {
		return nil, err
	}
	b := &Bindings{}
	symbol0, err := session.Resolve("s8")
	if err != nil {
		return nil, err
	}
	b.symbol0 = symbol0
	symbol1, err := session.Resolve("u8")
	if err != nil {
		return nil, err
	}
	b.symbol1 = symbol1
	symbol2, err := session.Resolve("s16")
	if err != nil {
		return nil, err
	}
	b.symbol2 = symbol2
	symbol3, err := session.Resolve("u16")
	if err != nil {
		return nil, err
	}
	b.symbol3 = symbol3
	symbol4, err := session.Resolve("s32")
	if err != nil {
		return nil, err
	}
	b.symbol4 = symbol4
	symbol5, err := session.Resolve("u32")
	if err != nil {
		return nil, err
	}
	b.symbol5 = symbol5
	symbol6, err := session.Resolve("s64")
	if err != nil {
		return nil, err
	}
	b.symbol6 = symbol6
	symbol7, err := session.Resolve("u64")
	if err != nil {
		return nil, err
	}
	b.symbol7 = symbol7
	symbol8, err := session.Resolve("f32")
	if err != nil {
		return nil, err
	}
	b.symbol8 = symbol8
	symbol9, err := session.Resolve("f64")
	if err != nil {
		return nil, err
	}
	b.symbol9 = symbol9
	symbol10, err := session.Resolve("truth")
	if err != nil {
		return nil, err
	}
	b.symbol10 = symbol10
	symbol11, err := session.Resolve("pointer")
	if err != nil {
		return nil, err
	}
	b.symbol11 = symbol11
	symbol12, err := session.Resolve("zero")
	if err != nil {
		return nil, err
	}
	b.symbol12 = symbol12
	symbol13, err := session.Resolve("empty")
	if err != nil {
		return nil, err
	}
	b.symbol13 = symbol13
	symbol14, err := session.Resolve("mixed")
	if err != nil {
		return nil, err
	}
	b.symbol14 = symbol14
	symbol15, err := session.Resolve("variable")
	if err != nil {
		return nil, err
	}
	b.symbol15 = symbol15
	symbol16, err := session.Resolve("promotions")
	if err != nil {
		return nil, err
	}
	b.symbol16 = symbol16
	symbol17, err := session.Resolve("empty_variable")
	if err != nil {
		return nil, err
	}
	b.symbol17 = symbol17
	symbol18, err := session.Resolve("mixed_variable")
	if err != nil {
		return nil, err
	}
	b.symbol18 = symbol18
	symbol19, err := session.Resolve("void_variable")
	if err != nil {
		return nil, err
	}
	b.symbol19 = symbol19
	symbol20, err := session.Resolve("adder_factory")
	if err != nil {
		return nil, err
	}
	b.symbol20 = symbol20
	symbol21, err := session.Resolve("apply_adder")
	if err != nil {
		return nil, err
	}
	b.symbol21 = symbol21
	symbol22, err := session.Resolve("variadic_factory")
	if err != nil {
		return nil, err
	}
	b.symbol22 = symbol22
	symbol23, err := session.Resolve("forward_variadic")
	if err != nil {
		return nil, err
	}
	b.symbol23 = symbol23
	symbol24, err := session.Resolve("data_pointer")
	if err != nil {
		return nil, err
	}
	b.symbol24 = symbol24
	return b, nil
}

func (b *Bindings) S8(p0 int8) (result int8, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol0.WithAddress(func(address uintptr) error {
		result = int8(C.dylib_go_42696e64696e6773_call0(C.uintptr_t(address), C.int32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) U8(p0 uint8) (result uint8, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol1.WithAddress(func(address uintptr) error {
		result = uint8(C.dylib_go_42696e64696e6773_call1(C.uintptr_t(address), C.uint32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) S16(p0 int16) (result int16, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol2.WithAddress(func(address uintptr) error {
		result = int16(C.dylib_go_42696e64696e6773_call2(C.uintptr_t(address), C.int32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) U16(p0 uint16) (result uint16, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol3.WithAddress(func(address uintptr) error {
		result = uint16(C.dylib_go_42696e64696e6773_call3(C.uintptr_t(address), C.uint32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) S32(p0 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol4.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call4(C.uintptr_t(address), C.int32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) U32(p0 uint32) (result uint32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol5.WithAddress(func(address uintptr) error {
		result = uint32(C.dylib_go_42696e64696e6773_call5(C.uintptr_t(address), C.uint32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) S64(p0 int64) (result int64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol6.WithAddress(func(address uintptr) error {
		result = int64(C.dylib_go_42696e64696e6773_call6(C.uintptr_t(address), C.int64_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) U64(p0 uint64) (result uint64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol7.WithAddress(func(address uintptr) error {
		result = uint64(C.dylib_go_42696e64696e6773_call7(C.uintptr_t(address), C.uint64_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) F32(p0 float32) (result float32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol8.WithAddress(func(address uintptr) error {
		result = float32(C.dylib_go_42696e64696e6773_call8(C.uintptr_t(address), C.float(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) F64(p0 float64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol9.WithAddress(func(address uintptr) error {
		result = float64(C.dylib_go_42696e64696e6773_call9(C.uintptr_t(address), C.double(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) Truth(p0 bool) (result bool, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol10.WithAddress(func(address uintptr) error {
		var c0 C.int32_t
		if p0 {
			c0 = 1
		}
		result = C.dylib_go_42696e64696e6773_call10(C.uintptr_t(address), c0) != 0
		return nil
	})
	return result, err
}

func (b *Bindings) Pointer(p0 unsafe.Pointer) (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol11.WithAddress(func(address uintptr) error {
		result = unsafe.Pointer(C.dylib_go_42696e64696e6773_call11(C.uintptr_t(address), p0))
		return nil
	})
	return result, err
}

func (b *Bindings) Zero() (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol12.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call12(C.uintptr_t(address)))
		return nil
	})
	return result, err
}

func (b *Bindings) Empty() error {
	if b == nil {
		return dylib.ErrClosed
	}
	return b.symbol13.WithAddress(func(address uintptr) error {
		C.dylib_go_42696e64696e6773_call13(C.uintptr_t(address))
		return nil
	})
}

func (b *Bindings) Mixed(p0 int32, p1 float64, p2 float32, p3 uint64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol14.WithAddress(func(address uintptr) error {
		result = float64(C.dylib_go_42696e64696e6773_call14(C.uintptr_t(address), C.int32_t(p0), C.double(p1), C.float(p2), C.uint64_t(p3)))
		return nil
	})
	return result, err
}

func (b *Bindings) Variable(p0 int32, p1 int8, p2 float32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol15.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call15(C.uintptr_t(address), C.int32_t(p0), C.int32_t(p1), C.float(p2)))
		return nil
	})
	return result, err
}

func (b *Bindings) Promotions(p0 int32, p1 int8, p2 uint8, p3 int16, p4 uint16, p5 float32, p6 bool, p7 int64, p8 uint64, p9 unsafe.Pointer) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol16.WithAddress(func(address uintptr) error {
		var c6 C.int32_t
		if p6 {
			c6 = 1
		}
		result = int32(C.dylib_go_42696e64696e6773_call16(C.uintptr_t(address), C.int32_t(p0), C.int32_t(p1), C.uint32_t(p2), C.int32_t(p3), C.uint32_t(p4), C.float(p5), c6, C.int64_t(p7), C.uint64_t(p8), p9))
		return nil
	})
	return result, err
}

func (b *Bindings) Empty_variable(p0 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol17.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call17(C.uintptr_t(address), C.int32_t(p0)))
		return nil
	})
	return result, err
}

func (b *Bindings) Mixed_variable(p0 float32, p1 int32, p2 int8, p3 float32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol18.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call18(C.uintptr_t(address), C.float(p0), C.int32_t(p1), C.int32_t(p2), C.float(p3)))
		return nil
	})
	return result, err
}

func (b *Bindings) Void_variable(p0 int32, p1 int16) error {
	if b == nil {
		return dylib.ErrClosed
	}
	return b.symbol19.WithAddress(func(address uintptr) error {
		C.dylib_go_42696e64696e6773_call19(C.uintptr_t(address), C.int32_t(p0), C.int32_t(p1))
		return nil
	})
}

func (b *Bindings) Adder_factory() (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol20.WithAddress(func(address uintptr) error {
		result = unsafe.Pointer(C.dylib_go_42696e64696e6773_call20(C.uintptr_t(address)))
		return nil
	})
	return result, err
}

func (b *Bindings) Apply_adder(p0 unsafe.Pointer, p1 int32, p2 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol21.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call21(C.uintptr_t(address), p0, C.int32_t(p1), C.int32_t(p2)))
		return nil
	})
	return result, err
}

func (b *Bindings) Variadic_factory() (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol22.WithAddress(func(address uintptr) error {
		result = unsafe.Pointer(C.dylib_go_42696e64696e6773_call22(C.uintptr_t(address)))
		return nil
	})
	return result, err
}

func (b *Bindings) Forward_variadic(p0 unsafe.Pointer, p1 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol23.WithAddress(func(address uintptr) error {
		result = int32(C.dylib_go_42696e64696e6773_call23(C.uintptr_t(address), p0, C.int32_t(p1)))
		return nil
	})
	return result, err
}

func (b *Bindings) Data_pointer() (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol24.WithAddress(func(address uintptr) error {
		result = unsafe.Pointer(C.dylib_go_42696e64696e6773_call24(C.uintptr_t(address)))
		return nil
	})
	return result, err
}
