// Code generated by compiler/clang. DO NOT EDIT.

//go:build llgo && cgo

package main

import (
	"fmt"
	dylib "github.com/cpunion/dylib-go"
	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
	"unsafe"
)

var _BindingsDeclarations = clang.Header{
	Target: clang.Target{Triple: "aarch64-pc-windows-msvc", OS: "windows", Arch: "arm64", PointerSize: 8},
	Functions: []clang.Declaration{
		{Name: "s8", Symbol: "s8", Signature: abi.Signature{Result: abi.I8, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I8}}},
		{Name: "u8", Symbol: "u8", Signature: abi.Signature{Result: abi.U8, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U8}}},
		{Name: "s16", Symbol: "s16", Signature: abi.Signature{Result: abi.I16, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I16}}},
		{Name: "u16", Symbol: "u16", Signature: abi.Signature{Result: abi.U16, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U16}}},
		{Name: "s32", Symbol: "s32", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32}}},
		{Name: "u32", Symbol: "u32", Signature: abi.Signature{Result: abi.U32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U32}}},
		{Name: "s64", Symbol: "s64", Signature: abi.Signature{Result: abi.I64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I64}}},
		{Name: "u64", Symbol: "u64", Signature: abi.Signature{Result: abi.U64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U64}}},
		{Name: "f32", Symbol: "f32", Signature: abi.Signature{Result: abi.F32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F32}}},
		{Name: "f64", Symbol: "f64", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F64}}},
		{Name: "truth", Symbol: "truth", Signature: abi.Signature{Result: abi.Bool, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Bool}}},
		{Name: "pointer", Symbol: "pointer", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer}}},
		{Name: "zero", Symbol: "zero", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
		{Name: "empty", Symbol: "empty", Signature: abi.Signature{Result: abi.Void, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
		{Name: "mixed", Symbol: "mixed", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.F64, abi.F32, abi.U64}}},
		{Name: "echo_pair", Symbol: "echo_pair", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}},
		{Name: "mutate_pair", Symbol: "mutate_pair", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Pointer, Elem: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}}, ResultType: &abi.TypeDesc{Type: abi.Pointer, Elem: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}}},
		{Name: "echo_outer", Symbol: "echo_outer", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "items", Type: abi.TypeDesc{Type: abi.Array, Len: 2, Elem: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}}, {Name: "values", Type: abi.TypeDesc{Type: abi.Array, Len: 2, Elem: &abi.TypeDesc{Type: abi.Array, Len: 3, Elem: &abi.TypeDesc{Type: abi.I32}}}}, {Name: "next", Type: abi.TypeDesc{Type: abi.Pointer}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "items", Type: abi.TypeDesc{Type: abi.Array, Len: 2, Elem: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}}, {Name: "values", Type: abi.TypeDesc{Type: abi.Array, Len: 2, Elem: &abi.TypeDesc{Type: abi.Array, Len: 3, Elem: &abi.TypeDesc{Type: abi.I32}}}}, {Name: "next", Type: abi.TypeDesc{Type: abi.Pointer}}}}}},
		{Name: "echo_floats", Symbol: "echo_floats", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "values", Type: abi.TypeDesc{Type: abi.Array, Len: 4, Elem: &abi.TypeDesc{Type: abi.F32}}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "values", Type: abi.TypeDesc{Type: abi.Array, Len: 4, Elem: &abi.TypeDesc{Type: abi.F32}}}}}}},
		{Name: "echo_small", Symbol: "echo_small", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "a", Type: abi.TypeDesc{Type: abi.I32}}, {Name: "b", Type: abi.TypeDesc{Type: abi.I32}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "a", Type: abi.TypeDesc{Type: abi.I32}}, {Name: "b", Type: abi.TypeDesc{Type: abi.I32}}}}}},
		{Name: "echo_mixed", Symbol: "echo_mixed", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tag", Type: abi.TypeDesc{Type: abi.I32}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tag", Type: abi.TypeDesc{Type: abi.I32}}}}}},
	},
	Records: []clang.Record{
		{Name: "Pair", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}, Layout: abi.Layout{Size: 24, Alignment: 8, Offsets: []uint64{0, 8, 16}}},
		{Name: "Outer", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "items", Type: abi.TypeDesc{Type: abi.Array, Len: 2, Elem: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}}, {Name: "values", Type: abi.TypeDesc{Type: abi.Array, Len: 2, Elem: &abi.TypeDesc{Type: abi.Array, Len: 3, Elem: &abi.TypeDesc{Type: abi.I32}}}}, {Name: "next", Type: abi.TypeDesc{Type: abi.Pointer}}}}, Layout: abi.Layout{Size: 80, Alignment: 8, Offsets: []uint64{0, 48, 72}}},
		{Name: "FloatVector", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "values", Type: abi.TypeDesc{Type: abi.Array, Len: 4, Elem: &abi.TypeDesc{Type: abi.F32}}}}}, Layout: abi.Layout{Size: 16, Alignment: 4, Offsets: []uint64{0}}},
		{Name: "Small", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "a", Type: abi.TypeDesc{Type: abi.I32}}, {Name: "b", Type: abi.TypeDesc{Type: abi.I32}}}}, Layout: abi.Layout{Size: 8, Alignment: 4, Offsets: []uint64{0, 4}}},
		{Name: "MixedPair", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tag", Type: abi.TypeDesc{Type: abi.I32}}}}, Layout: abi.Layout{Size: 16, Alignment: 8, Offsets: []uint64{0, 8}}},
	},
}

// BindingsRecord0 describes Pair; pointer fields are caller-managed native addresses.
//
//llgo:type C
type BindingsRecord0 struct {
	Tag   int8
	Value float64
	Tail  int16
}

// BindingsRecord1 describes Outer; pointer fields are caller-managed native addresses.
//
//llgo:type C
type BindingsRecord1 struct {
	Items  [2]BindingsRecord0
	Values [2][3]int32
	Next   unsafe.Pointer
}

// BindingsRecord2 describes FloatVector; pointer fields are caller-managed native addresses.
//
//llgo:type C
type BindingsRecord2 struct {
	Values [4]float32
}

// BindingsRecord3 describes Small; pointer fields are caller-managed native addresses.
//
//llgo:type C
type BindingsRecord3 struct {
	A int32
	B int32
}

// BindingsRecord4 describes MixedPair; pointer fields are caller-managed native addresses.
//
//llgo:type C
type BindingsRecord4 struct {
	Value float64
	Tag   int32
}

// Bindings retains symbol handles; its caller owns the Session.
type Bindings struct {
	symbol0  *dylib.Symbol
	symbol1  *dylib.Symbol
	symbol2  *dylib.Symbol
	symbol3  *dylib.Symbol
	symbol4  *dylib.Symbol
	symbol5  *dylib.Symbol
	symbol6  *dylib.Symbol
	symbol7  *dylib.Symbol
	symbol8  *dylib.Symbol
	symbol9  *dylib.Symbol
	symbol10 *dylib.Symbol
	symbol11 *dylib.Symbol
	symbol12 *dylib.Symbol
	symbol13 *dylib.Symbol
	symbol14 *dylib.Symbol
	symbol15 *dylib.Symbol
	symbol16 *dylib.Symbol
	symbol17 *dylib.Symbol
	symbol18 *dylib.Symbol
	symbol19 *dylib.Symbol
	symbol20 *dylib.Symbol
}

// NewBindings validates the host and resolves each requested export.
func NewBindings(session *dylib.Session) (*Bindings, error) {
	if session == nil {
		return nil, dylib.ErrClosed
	}
	if err := _BindingsDeclarations.Target.CheckHost(); err != nil {
		return nil, err
	}
	b := &Bindings{}
	if uint64(unsafe.Sizeof(BindingsRecord0{})) != 24 || uint64(unsafe.Alignof(BindingsRecord0{})) != 8 || uint64(unsafe.Offsetof(BindingsRecord0{}.Tag)) != 0 || uint64(unsafe.Offsetof(BindingsRecord0{}.Value)) != 8 || uint64(unsafe.Offsetof(BindingsRecord0{}.Tail)) != 16 {
		return nil, fmt.Errorf("clang: compiler/llgo layout mismatch for Pair")
	}
	if uint64(unsafe.Sizeof(BindingsRecord1{})) != 80 || uint64(unsafe.Alignof(BindingsRecord1{})) != 8 || uint64(unsafe.Offsetof(BindingsRecord1{}.Items)) != 0 || uint64(unsafe.Offsetof(BindingsRecord1{}.Values)) != 48 || uint64(unsafe.Offsetof(BindingsRecord1{}.Next)) != 72 {
		return nil, fmt.Errorf("clang: compiler/llgo layout mismatch for Outer")
	}
	if uint64(unsafe.Sizeof(BindingsRecord2{})) != 16 || uint64(unsafe.Alignof(BindingsRecord2{})) != 4 || uint64(unsafe.Offsetof(BindingsRecord2{}.Values)) != 0 {
		return nil, fmt.Errorf("clang: compiler/llgo layout mismatch for FloatVector")
	}
	if uint64(unsafe.Sizeof(BindingsRecord3{})) != 8 || uint64(unsafe.Alignof(BindingsRecord3{})) != 4 || uint64(unsafe.Offsetof(BindingsRecord3{}.A)) != 0 || uint64(unsafe.Offsetof(BindingsRecord3{}.B)) != 4 {
		return nil, fmt.Errorf("clang: compiler/llgo layout mismatch for Small")
	}
	if uint64(unsafe.Sizeof(BindingsRecord4{})) != 16 || uint64(unsafe.Alignof(BindingsRecord4{})) != 8 || uint64(unsafe.Offsetof(BindingsRecord4{}.Value)) != 0 || uint64(unsafe.Offsetof(BindingsRecord4{}.Tag)) != 8 {
		return nil, fmt.Errorf("clang: compiler/llgo layout mismatch for MixedPair")
	}
	symbol0, err := session.Resolve("s8")
	if err != nil {
		return nil, err
	}
	b.symbol0 = symbol0
	symbol1, err := session.Resolve("u8")
	if err != nil {
		return nil, err
	}
	b.symbol1 = symbol1
	symbol2, err := session.Resolve("s16")
	if err != nil {
		return nil, err
	}
	b.symbol2 = symbol2
	symbol3, err := session.Resolve("u16")
	if err != nil {
		return nil, err
	}
	b.symbol3 = symbol3
	symbol4, err := session.Resolve("s32")
	if err != nil {
		return nil, err
	}
	b.symbol4 = symbol4
	symbol5, err := session.Resolve("u32")
	if err != nil {
		return nil, err
	}
	b.symbol5 = symbol5
	symbol6, err := session.Resolve("s64")
	if err != nil {
		return nil, err
	}
	b.symbol6 = symbol6
	symbol7, err := session.Resolve("u64")
	if err != nil {
		return nil, err
	}
	b.symbol7 = symbol7
	symbol8, err := session.Resolve("f32")
	if err != nil {
		return nil, err
	}
	b.symbol8 = symbol8
	symbol9, err := session.Resolve("f64")
	if err != nil {
		return nil, err
	}
	b.symbol9 = symbol9
	symbol10, err := session.Resolve("truth")
	if err != nil {
		return nil, err
	}
	b.symbol10 = symbol10
	symbol11, err := session.Resolve("pointer")
	if err != nil {
		return nil, err
	}
	b.symbol11 = symbol11
	symbol12, err := session.Resolve("zero")
	if err != nil {
		return nil, err
	}
	b.symbol12 = symbol12
	symbol13, err := session.Resolve("empty")
	if err != nil {
		return nil, err
	}
	b.symbol13 = symbol13
	symbol14, err := session.Resolve("mixed")
	if err != nil {
		return nil, err
	}
	b.symbol14 = symbol14
	symbol15, err := session.Resolve("echo_pair")
	if err != nil {
		return nil, err
	}
	b.symbol15 = symbol15
	symbol16, err := session.Resolve("mutate_pair")
	if err != nil {
		return nil, err
	}
	b.symbol16 = symbol16
	symbol17, err := session.Resolve("echo_outer")
	if err != nil {
		return nil, err
	}
	b.symbol17 = symbol17
	symbol18, err := session.Resolve("echo_floats")
	if err != nil {
		return nil, err
	}
	b.symbol18 = symbol18
	symbol19, err := session.Resolve("echo_small")
	if err != nil {
		return nil, err
	}
	b.symbol19 = symbol19
	symbol20, err := session.Resolve("echo_mixed")
	if err != nil {
		return nil, err
	}
	b.symbol20 = symbol20
	return b, nil
}

//llgo:type C
type _BindingsFunction0 func(p0 int8) int8

func (b *Bindings) S8(p0 int8) (result int8, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol0.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction0)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction1 func(p0 uint8) uint8

func (b *Bindings) U8(p0 uint8) (result uint8, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol1.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction1)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction2 func(p0 int16) int16

func (b *Bindings) S16(p0 int16) (result int16, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol2.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction2)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction3 func(p0 uint16) uint16

func (b *Bindings) U16(p0 uint16) (result uint16, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol3.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction3)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction4 func(p0 int32) int32

func (b *Bindings) S32(p0 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol4.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction4)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction5 func(p0 uint32) uint32

func (b *Bindings) U32(p0 uint32) (result uint32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol5.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction5)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction6 func(p0 int64) int64

func (b *Bindings) S64(p0 int64) (result int64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol6.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction6)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction7 func(p0 uint64) uint64

func (b *Bindings) U64(p0 uint64) (result uint64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol7.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction7)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction8 func(p0 float32) float32

func (b *Bindings) F32(p0 float32) (result float32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol8.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction8)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction9 func(p0 float64) float64

func (b *Bindings) F64(p0 float64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol9.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction9)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction10 func(p0 bool) bool

func (b *Bindings) Truth(p0 bool) (result bool, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol10.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction10)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction11 func(p0 unsafe.Pointer) unsafe.Pointer

func (b *Bindings) Pointer(p0 unsafe.Pointer) (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol11.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction11)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction12 func() int32

func (b *Bindings) Zero() (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol12.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction12)(unsafe.Pointer(&address))
		result = function()
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction13 func()

func (b *Bindings) Empty() error {
	if b == nil {
		return dylib.ErrClosed
	}
	return b.symbol13.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction13)(unsafe.Pointer(&address))
		function()
		return nil
	})
}

//llgo:type C
type _BindingsFunction14 func(p0 int32, p1 float64, p2 float32, p3 uint64) float64

func (b *Bindings) Mixed(p0 int32, p1 float64, p2 float32, p3 uint64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol14.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction14)(unsafe.Pointer(&address))
		result = function(p0, p1, p2, p3)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction15 func(p0 BindingsRecord0) BindingsRecord0

func (b *Bindings) Echo_pair(p0 BindingsRecord0) (result BindingsRecord0, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol15.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction15)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction16 func(p0 *BindingsRecord0) *BindingsRecord0

func (b *Bindings) Mutate_pair(p0 *BindingsRecord0) (result *BindingsRecord0, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol16.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction16)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction17 func(p0 BindingsRecord1) BindingsRecord1

func (b *Bindings) Echo_outer(p0 BindingsRecord1) (result BindingsRecord1, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol17.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction17)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction18 func(p0 BindingsRecord2) BindingsRecord2

func (b *Bindings) Echo_floats(p0 BindingsRecord2) (result BindingsRecord2, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol18.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction18)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction19 func(p0 BindingsRecord3) BindingsRecord3

func (b *Bindings) Echo_small(p0 BindingsRecord3) (result BindingsRecord3, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol19.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction19)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction20 func(p0 BindingsRecord4) BindingsRecord4

func (b *Bindings) Echo_mixed(p0 BindingsRecord4) (result BindingsRecord4, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol20.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction20)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}
