// Code generated by compiler/clang. DO NOT EDIT.

//go:build llgo && cgo

package main

import (
	dylib "github.com/cpunion/dylib-go"
	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
	"unsafe"
)

var _BindingsDeclarations = clang.Header{
	Target: clang.Target{Triple: "aarch64-pc-windows-msvc", OS: "windows", Arch: "arm64", PointerSize: 8},
	Functions: []clang.Declaration{
		{Name: "s8", Symbol: "s8", Signature: abi.Signature{Result: abi.I8, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I8}}},
		{Name: "u8", Symbol: "u8", Signature: abi.Signature{Result: abi.U8, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U8}}},
		{Name: "s16", Symbol: "s16", Signature: abi.Signature{Result: abi.I16, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I16}}},
		{Name: "u16", Symbol: "u16", Signature: abi.Signature{Result: abi.U16, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U16}}},
		{Name: "s32", Symbol: "s32", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32}}},
		{Name: "u32", Symbol: "u32", Signature: abi.Signature{Result: abi.U32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U32}}},
		{Name: "s64", Symbol: "s64", Signature: abi.Signature{Result: abi.I64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I64}}},
		{Name: "u64", Symbol: "u64", Signature: abi.Signature{Result: abi.U64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.U64}}},
		{Name: "f32", Symbol: "f32", Signature: abi.Signature{Result: abi.F32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F32}}},
		{Name: "f64", Symbol: "f64", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F64}}},
		{Name: "truth", Symbol: "truth", Signature: abi.Signature{Result: abi.Bool, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Bool}}},
		{Name: "pointer", Symbol: "pointer", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer}}},
		{Name: "zero", Symbol: "zero", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
		{Name: "empty", Symbol: "empty", Signature: abi.Signature{Result: abi.Void, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{}}},
		{Name: "mixed", Symbol: "mixed", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.F64, abi.F32, abi.U64}}},
	},
}

// Bindings retains symbol handles; its caller owns the Session.
type Bindings struct {
	symbol0  *dylib.Symbol
	symbol1  *dylib.Symbol
	symbol2  *dylib.Symbol
	symbol3  *dylib.Symbol
	symbol4  *dylib.Symbol
	symbol5  *dylib.Symbol
	symbol6  *dylib.Symbol
	symbol7  *dylib.Symbol
	symbol8  *dylib.Symbol
	symbol9  *dylib.Symbol
	symbol10 *dylib.Symbol
	symbol11 *dylib.Symbol
	symbol12 *dylib.Symbol
	symbol13 *dylib.Symbol
	symbol14 *dylib.Symbol
}

// NewBindings validates the host and resolves each requested export.
func NewBindings(session *dylib.Session) (*Bindings, error) {
	if session == nil {
		return nil, dylib.ErrClosed
	}
	b := &Bindings{}
	if _, err := _BindingsDeclarations.ForHost("s8"); err != nil {
		return nil, err
	}
	symbol0, err := session.Resolve("s8")
	if err != nil {
		return nil, err
	}
	b.symbol0 = symbol0
	if _, err := _BindingsDeclarations.ForHost("u8"); err != nil {
		return nil, err
	}
	symbol1, err := session.Resolve("u8")
	if err != nil {
		return nil, err
	}
	b.symbol1 = symbol1
	if _, err := _BindingsDeclarations.ForHost("s16"); err != nil {
		return nil, err
	}
	symbol2, err := session.Resolve("s16")
	if err != nil {
		return nil, err
	}
	b.symbol2 = symbol2
	if _, err := _BindingsDeclarations.ForHost("u16"); err != nil {
		return nil, err
	}
	symbol3, err := session.Resolve("u16")
	if err != nil {
		return nil, err
	}
	b.symbol3 = symbol3
	if _, err := _BindingsDeclarations.ForHost("s32"); err != nil {
		return nil, err
	}
	symbol4, err := session.Resolve("s32")
	if err != nil {
		return nil, err
	}
	b.symbol4 = symbol4
	if _, err := _BindingsDeclarations.ForHost("u32"); err != nil {
		return nil, err
	}
	symbol5, err := session.Resolve("u32")
	if err != nil {
		return nil, err
	}
	b.symbol5 = symbol5
	if _, err := _BindingsDeclarations.ForHost("s64"); err != nil {
		return nil, err
	}
	symbol6, err := session.Resolve("s64")
	if err != nil {
		return nil, err
	}
	b.symbol6 = symbol6
	if _, err := _BindingsDeclarations.ForHost("u64"); err != nil {
		return nil, err
	}
	symbol7, err := session.Resolve("u64")
	if err != nil {
		return nil, err
	}
	b.symbol7 = symbol7
	if _, err := _BindingsDeclarations.ForHost("f32"); err != nil {
		return nil, err
	}
	symbol8, err := session.Resolve("f32")
	if err != nil {
		return nil, err
	}
	b.symbol8 = symbol8
	if _, err := _BindingsDeclarations.ForHost("f64"); err != nil {
		return nil, err
	}
	symbol9, err := session.Resolve("f64")
	if err != nil {
		return nil, err
	}
	b.symbol9 = symbol9
	if _, err := _BindingsDeclarations.ForHost("truth"); err != nil {
		return nil, err
	}
	symbol10, err := session.Resolve("truth")
	if err != nil {
		return nil, err
	}
	b.symbol10 = symbol10
	if _, err := _BindingsDeclarations.ForHost("pointer"); err != nil {
		return nil, err
	}
	symbol11, err := session.Resolve("pointer")
	if err != nil {
		return nil, err
	}
	b.symbol11 = symbol11
	if _, err := _BindingsDeclarations.ForHost("zero"); err != nil {
		return nil, err
	}
	symbol12, err := session.Resolve("zero")
	if err != nil {
		return nil, err
	}
	b.symbol12 = symbol12
	if _, err := _BindingsDeclarations.ForHost("empty"); err != nil {
		return nil, err
	}
	symbol13, err := session.Resolve("empty")
	if err != nil {
		return nil, err
	}
	b.symbol13 = symbol13
	if _, err := _BindingsDeclarations.ForHost("mixed"); err != nil {
		return nil, err
	}
	symbol14, err := session.Resolve("mixed")
	if err != nil {
		return nil, err
	}
	b.symbol14 = symbol14
	return b, nil
}

//llgo:type C
type _BindingsFunction0 func(p0 int8) int8

func (b *Bindings) S8(p0 int8) (result int8, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol0.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction0)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction1 func(p0 uint8) uint8

func (b *Bindings) U8(p0 uint8) (result uint8, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol1.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction1)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction2 func(p0 int16) int16

func (b *Bindings) S16(p0 int16) (result int16, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol2.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction2)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction3 func(p0 uint16) uint16

func (b *Bindings) U16(p0 uint16) (result uint16, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol3.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction3)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction4 func(p0 int32) int32

func (b *Bindings) S32(p0 int32) (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol4.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction4)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction5 func(p0 uint32) uint32

func (b *Bindings) U32(p0 uint32) (result uint32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol5.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction5)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction6 func(p0 int64) int64

func (b *Bindings) S64(p0 int64) (result int64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol6.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction6)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction7 func(p0 uint64) uint64

func (b *Bindings) U64(p0 uint64) (result uint64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol7.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction7)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction8 func(p0 float32) float32

func (b *Bindings) F32(p0 float32) (result float32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol8.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction8)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction9 func(p0 float64) float64

func (b *Bindings) F64(p0 float64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol9.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction9)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction10 func(p0 bool) bool

func (b *Bindings) Truth(p0 bool) (result bool, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol10.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction10)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction11 func(p0 unsafe.Pointer) unsafe.Pointer

func (b *Bindings) Pointer(p0 unsafe.Pointer) (result unsafe.Pointer, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol11.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction11)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction12 func() int32

func (b *Bindings) Zero() (result int32, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol12.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction12)(unsafe.Pointer(&address))
		result = function()
		return nil
	})
	return result, err
}

//llgo:type C
type _BindingsFunction13 func()

func (b *Bindings) Empty() error {
	if b == nil {
		return dylib.ErrClosed
	}
	return b.symbol13.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction13)(unsafe.Pointer(&address))
		function()
		return nil
	})
}

//llgo:type C
type _BindingsFunction14 func(p0 int32, p1 float64, p2 float32, p3 uint64) float64

func (b *Bindings) Mixed(p0 int32, p1 float64, p2 float32, p3 uint64) (result float64, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol14.WithAddress(func(address uintptr) error {
		function := *(*_BindingsFunction14)(unsafe.Pointer(&address))
		result = function(p0, p1, p2, p3)
		return nil
	})
	return result, err
}
