// Code generated by compiler/clang. DO NOT EDIT.

//go:build llgo && cgo

package main

import (
	"fmt"
	dylib "github.com/cpunion/dylib-go"
	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
	"unsafe"
)

var _PackedBindingsDeclarations = clang.Header{
	Target: clang.Target{Triple: "aarch64-pc-windows-msvc", OS: "windows", Arch: "arm64", PointerSize: 8},
	Functions: []clang.Declaration{
		{Name: "echo_pair", Symbol: "echo_pair", Signature: abi.Signature{Result: abi.Struct, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Struct}, ArgTypes: []abi.TypeDesc{abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}, ResultType: &abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}}},
	},
	Records: []clang.Record{
		{Name: "Pair", Description: abi.TypeDesc{Type: abi.Struct, Fields: []abi.Field{{Name: "tag", Type: abi.TypeDesc{Type: abi.I8}}, {Name: "value", Type: abi.TypeDesc{Type: abi.F64}}, {Name: "tail", Type: abi.TypeDesc{Type: abi.I16}}}}, Layout: abi.Layout{Size: 11, Alignment: 1, Offsets: []uint64{0, 1, 9}}},
	},
}

// PackedBindingsRecord0 describes Pair; pointer fields are caller-managed native addresses.
//
//llgo:type C
type PackedBindingsRecord0 struct {
	Tag   int8
	Value float64
	Tail  int16
}

// PackedBindings retains symbol handles; its caller owns the Session.
type PackedBindings struct {
	symbol0 *dylib.Symbol
}

// NewPackedBindings validates the host and resolves each requested export.
func NewPackedBindings(session *dylib.Session) (*PackedBindings, error) {
	if session == nil {
		return nil, dylib.ErrClosed
	}
	if err := _PackedBindingsDeclarations.Target.CheckHost(); err != nil {
		return nil, err
	}
	b := &PackedBindings{}
	if uint64(unsafe.Sizeof(PackedBindingsRecord0{})) != 11 || uint64(unsafe.Alignof(PackedBindingsRecord0{})) != 1 || uint64(unsafe.Offsetof(PackedBindingsRecord0{}.Tag)) != 0 || uint64(unsafe.Offsetof(PackedBindingsRecord0{}.Value)) != 1 || uint64(unsafe.Offsetof(PackedBindingsRecord0{}.Tail)) != 9 {
		return nil, fmt.Errorf("clang: compiler/llgo layout mismatch for Pair")
	}
	symbol0, err := session.Resolve("echo_pair")
	if err != nil {
		return nil, err
	}
	b.symbol0 = symbol0
	return b, nil
}

//llgo:type C
type _PackedBindingsFunction0 func(p0 PackedBindingsRecord0) PackedBindingsRecord0

func (b *PackedBindings) Echo_pair(p0 PackedBindingsRecord0) (result PackedBindingsRecord0, err error) {
	if b == nil {
		return result, dylib.ErrClosed
	}
	err = b.symbol0.WithAddress(func(address uintptr) error {
		function := *(*_PackedBindingsFunction0)(unsafe.Pointer(&address))
		result = function(p0)
		return nil
	})
	return result, err
}
