package clang

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"

	"github.com/cpunion/dylib-go/abi"
)

// GoSource renders target-qualified declarations as a Go Header variable. The
// generated source uses ForHost and Session.Bind like declarations parsed at
// runtime; it adds no linkname directives or implicit library dependencies.
func (h *Header) GoSource(packageName, variableName string) ([]byte, error) {
	validName := func(name string) bool {
		return name != "_" && token.IsIdentifier(name) && !token.Lookup(name).IsKeyword()
	}
	if h == nil || !validName(packageName) || !validName(variableName) || len(h.Functions) == 0 {
		return nil, fmt.Errorf("clang: expected declarations and valid Go package/variable names")
	}
	target, err := parseTarget(h.Target.Triple, h.Target.PointerSize)
	if err != nil || target != h.Target {
		return nil, fmt.Errorf("clang: inconsistent declaration target")
	}
	if err := h.validateDescriptions(); err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by compiler/clang. DO NOT EDIT.\n\npackage %s\n\nimport (\n\"github.com/cpunion/dylib-go/abi\"\nclang \"github.com/cpunion/dylib-go/compiler/clang\"\n)\n", packageName)
	fmt.Fprintf(&output, "\nvar %s = clang.Header{\nTarget: clang.Target{Triple: %q, OS: %q, Arch: %q, PointerSize: %d},\nFunctions: []clang.Declaration{\n", variableName, target.Triple, target.OS, target.Arch, target.PointerSize)
	seen := make(map[string]bool)
	for _, function := range h.Functions {
		if !cIdentifier(function.Name) || function.Symbol == "" || seen[function.Name] {
			return nil, fmt.Errorf("clang: invalid or duplicate declaration %q", function.Name)
		}
		seen[function.Name] = true
		signature := function.Signature
		fmt.Fprintf(&output, "{Name:%q, Symbol:%q, Signature:abi.Signature{Result:abi.%s, Convention:abi.%s, Variadic:%t, FixedArgs:%d, Args:[]abi.Type{", function.Name, function.Symbol, typeName(signature.Result), conventionName(signature.Convention), signature.Variadic, signature.FixedArgs)
		for _, parameter := range signature.Args {
			fmt.Fprintf(&output, "abi.%s,", typeName(parameter))
		}
		fmt.Fprint(&output, "}")
		if len(signature.ArgTypes) != 0 {
			fmt.Fprint(&output, ",ArgTypes:[]abi.TypeDesc{")
			for _, description := range signature.ArgTypes {
				writeDescription(&output, description)
				fmt.Fprint(&output, ",")
			}
			fmt.Fprint(&output, "}")
		}
		if signature.ResultType != nil {
			fmt.Fprint(&output, ",ResultType:&")
			writeDescription(&output, *signature.ResultType)
		}
		fmt.Fprint(&output, "}},\n")
	}
	fmt.Fprint(&output, "},\n")
	if len(h.Records) != 0 {
		fmt.Fprint(&output, "Records:[]clang.Record{\n")
		for _, record := range h.Records {
			if err := validRecordLayout(record); err != nil {
				return nil, err
			}
			fmt.Fprintf(&output, "{Name:%q,Description:", record.Name)
			writeDescription(&output, record.Description)
			fmt.Fprintf(&output, ",Layout:abi.Layout{Size:%d,Alignment:%d,Offsets:[]uint64{", record.Layout.Size, record.Layout.Alignment)
			for _, offset := range record.Layout.Offsets {
				fmt.Fprintf(&output, "%d,", offset)
			}
			fmt.Fprint(&output, "}}},\n")
		}
		fmt.Fprint(&output, "},\n")
	}
	fmt.Fprint(&output, "}\n")
	return format.Source(output.Bytes())
}

func writeDescription(output *bytes.Buffer, description abi.TypeDesc) {
	fmt.Fprintf(output, "abi.TypeDesc{Type:abi.%s", typeName(description.Type))
	if description.Len != 0 {
		fmt.Fprintf(output, ",Len:%d", description.Len)
	}
	if description.Elem != nil {
		fmt.Fprint(output, ",Elem:&")
		writeDescription(output, *description.Elem)
	}
	if len(description.Fields) != 0 {
		fmt.Fprint(output, ",Fields:[]abi.Field{")
		for _, field := range description.Fields {
			fmt.Fprintf(output, "{Name:%q,Type:", field.Name)
			writeDescription(output, field.Type)
			fmt.Fprint(output, "},")
		}
		fmt.Fprint(output, "}")
	}
	fmt.Fprint(output, "}")
}

func typeName(id abi.Type) string {
	return map[abi.Type]string{abi.Void: "Void", abi.I8: "I8", abi.U8: "U8", abi.I16: "I16", abi.U16: "U16", abi.I32: "I32", abi.U32: "U32", abi.I64: "I64", abi.U64: "U64", abi.F32: "F32", abi.F64: "F64", abi.Bool: "Bool", abi.Pointer: "Pointer", abi.Struct: "Struct", abi.Array: "Array"}[id]
}

func conventionName(id abi.Convention) string {
	return map[abi.Convention]string{abi.Default: "Default", abi.CDecl: "CDecl", abi.StdCall: "StdCall", abi.FastCall: "FastCall"}[id]
}
