#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
go test ./...
CGO_ENABLED=0 go test ./...
go vet ./...
if [ "${DYLIB_TEST_FFI:-0}" = 1 ]; then
    go test -race -tags libffi ./...
fi
if [ "${DYLIB_TEST_LLGO:-0}" = 1 ]; then
    llgo test ./...
    if [ "${DYLIB_TEST_FFI:-0}" = 1 ]; then
        llgo test -tags libffi ./...
    fi
fi
