// Code generated by compiler/clang. DO NOT EDIT.

//go:build libffi && cgo

package main

import (
	"github.com/cpunion/dylib-go/abi"
	clang "github.com/cpunion/dylib-go/compiler/clang"
)

var Declarations = clang.Header{
	Target: clang.Target{Triple: "aarch64-unknown-linux-gnu", OS: "linux", Arch: "arm64", PointerSize: 8},
	Functions: []clang.Declaration{
		{Name: "add", Symbol: "add", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.I32, abi.I32}}},
		{Name: "mixed", Symbol: "mixed", Signature: abi.Signature{Result: abi.F64, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.F32, abi.F64}}},
		{Name: "truth", Symbol: "truth", Signature: abi.Signature{Result: abi.Bool, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Bool}}},
		{Name: "pointer", Symbol: "pointer", Signature: abi.Signature{Result: abi.Pointer, Convention: abi.CDecl, Variadic: false, FixedArgs: 0, Args: []abi.Type{abi.Pointer}}},
		{Name: "variable", Symbol: "variable", Signature: abi.Signature{Result: abi.I32, Convention: abi.CDecl, Variadic: true, FixedArgs: 1, Args: []abi.Type{abi.I32}}},
	},
}
